require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

def ccache_enabled?(podfile_properties)
  # Environment variable takes precedence
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']
  
  # Fall back to Podfile properties
  podfile_properties['apple.ccacheEnabled'] == 'true'
end

ENV['RCT_NEW_ARCH_ENABLED'] ||= '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
ENV['RCT_USE_RN_DEP'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'

prepare_react_native_project!

target 'Nuvio' do
  use_expo_modules!(exclude: ['expo-live-activity'])

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(\'expo/bin/autolinking\')',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  # KSPlayer dependencies
  pod 'KSPlayer', :path => '../KSPlayer'
  pod 'DisplayCriteria', :path => '../KSPlayer', :modular_headers => true
  pod 'FFmpegKit', :git => 'https://github.com/kingslay/FFmpegKit.git', :branch => 'main', :modular_headers => true
  pod 'Libass', :git => 'https://github.com/kingslay/FFmpegKit.git', :branch => 'main'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => true,
      :ccache_enabled => ccache_enabled?(podfile_properties),
    )

    # Exclude pods that don't support Mac Catalyst
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if ['react-native-google-cast', 'GoogleCast'].include?(target.name)
          config.build_settings['SUPPORTS_MACCATALYST'] = 'NO'
        end
      end
    end

    # Fix "bundle format is ambiguous" codesign error for Mac Catalyst.
    # The React and ReactNativeDependencies xcframework maccatalyst slices have a hybrid
    # bundle structure (flat iOS binary + macOS Versions/ directory) that confuses codesign.
    # Removing Versions/ after copy makes them clean flat frameworks codesign can handle.
    frameworks_script = File.join(installer.sandbox.root, 'Target Support Files', 'Pods-Nuvio', 'Pods-Nuvio-frameworks.sh')
    if File.exist?(frameworks_script)
      script = File.read(frameworks_script)
      # Only React.framework and ReactNativeDependencies.framework ship hybrid Catalyst
      # slices that need their Versions/ directory removed before signing. Hermes is a
      # normal symlinked macOS framework, so deleting Versions/ breaks its layout.
      script.gsub!(
        '  code_sign_if_enabled "${destination}/$(basename "$1")"',
        "  framework_path=\"${destination}/$(basename \"$1\")\"\n  framework_name=\"$(basename \"$framework_path\")\"\n  case \"$framework_name\" in\n    React.framework|ReactNativeDependencies.framework)\n      rm -rf \"$framework_path/Versions\"\n      if [ -f \"$framework_path/Resources/Info.plist\" ] && [ ! -f \"$framework_path/Info.plist\" ]; then\n        cp \"$framework_path/Resources/Info.plist\" \"$framework_path/Info.plist\"\n      fi\n      ;;\n  esac\n  if [ \"$framework_name\" = \"ReactNativeDependencies.framework\" ]; then\n    find \"$framework_path\" -type d -name \"*.bundle\" -print0 | while IFS= read -r -d '' bundle; do\n      code_sign_if_enabled \"$bundle\"\n    done\n  fi\n  code_sign_if_enabled \"$framework_path\""
      )
      # Remove --preserve-metadata which can produce invalid signatures for Catalyst
      script.gsub!('--preserve-metadata=identifier,entitlements ', '')
      File.write(frameworks_script, script)
    end
  end
end
